In [2]:
import numpy as np

## Inverse
Use an inverse to solve a system of equations

1x + 2y = 7  
-3x + 4y = -9  
Can solve this the algebra 1 way  
Or we can use matrices:  
A =[[1, 2],[-3, 4]]  
x = [x, y]  
b = [7, -9]  


Ax = b  
x = A<sup>-1</sup> * b  

In [24]:
A = np.array([[1, 2], [-3, 4]])
b = np.array([7, -9])

In [28]:
x = np.asmatrix(A).getI().dot(b)
print(x)

[[4.6 1.2]]


## Rank

In [51]:
A = np.matrix([[1, 2, 3], [4, 1, 5], [2, -3, -1]])

In [45]:
np.linalg.matrix_rank(A)

2

In [57]:
# replace rightmost column with new column
new_col = np.array([[x] for x in [11, 13, 17]])
A_prime = np.concatenate((A[:, :-1], new_col), axis=1)

In [54]:
A_prime

matrix([[ 1,  2, 11],
        [ 4,  1, 13],
        [ 2, -3, 17]])

In [56]:
np.linalg.matrix_rank(A_prime)

3

## Eigenvectors and Eigenvalues

In [29]:
A = np.array([[2,1],[4,3]])
w, v = np.linalg.eig(A)

In [30]:
print(w) # eigenvalues

[0.43844719 4.56155281]


In [31]:
print(v) # eigenvectors

[[-0.5392856  -0.36365914]
 [ 0.84212294 -0.93153209]]


In [32]:
A.dot(v)

array([[-0.23644825, -1.65885036],
       [ 0.36922643, -4.24923282]])

In [33]:
v * w

array([[-0.23644825, -1.65885036],
       [ 0.36922643, -4.24923282]])